export const CHANGE_PAGE = 'CHANGE_PAGE';
export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
export const REMOVE_SUBSCRIPTION = 'REMOVE_SUBSCRIPTION';
export const UPDATE_SUBSCRIPTIONS = 'UPDATE_SUBSCRIPTIONS';